<?php

/**
 * Base class that represents a row from the 'visit' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 06/21/11 06:25:46
 *
 * @package    lib.model.om
 */
abstract class BaseVisit extends BaseObject  implements Persistent {


  const PEER = 'VisitPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        VisitPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the patient_id field.
	 * @var        int
	 */
	protected $patient_id;

	/**
	 * The value for the doctor_id field.
	 * @var        int
	 */
	protected $doctor_id;

	/**
	 * The value for the ward_bed_id field.
	 * @var        int
	 */
	protected $ward_bed_id;

	/**
	 * The value for the ward_doc_id field.
	 * @var        int
	 */
	protected $ward_doc_id;

	/**
	 * The value for the visit_type field.
	 * @var        string
	 */
	protected $visit_type;

	/**
	 * The value for the medicine field.
	 * @var        string
	 */
	protected $medicine;

	/**
	 * The value for the bp field.
	 * @var        string
	 */
	protected $bp;

	/**
	 * The value for the temp field.
	 * @var        string
	 */
	protected $temp;

	/**
	 * The value for the pulse field.
	 * @var        string
	 */
	protected $pulse;

	/**
	 * The value for the injection field.
	 * @var        string
	 */
	protected $injection;

	/**
	 * The value for the diet field.
	 * @var        string
	 */
	protected $diet;

	/**
	 * The value for the description field.
	 * @var        string
	 */
	protected $description;

	/**
	 * The value for the time field.
	 * @var        string
	 */
	protected $time;

	/**
	 * The value for the visit_date field.
	 * @var        string
	 */
	protected $visit_date;

	/**
	 * The value for the fee field.
	 * @var        string
	 */
	protected $fee;

	/**
	 * The value for the fee_paid field.
	 * @var        string
	 */
	protected $fee_paid;

	/**
	 * The value for the status field.
	 * @var        string
	 */
	protected $status;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        Patient
	 */
	protected $aPatient;

	/**
	 * @var        Employee
	 */
	protected $aEmployeeRelatedByDoctorId;

	/**
	 * @var        WardBed
	 */
	protected $aWardBed;

	/**
	 * @var        Employee
	 */
	protected $aEmployeeRelatedByWardDocId;

	/**
	 * @var        array LabReport[] Collection to store aggregation of LabReport objects.
	 */
	protected $collLabReports;

	/**
	 * @var        Criteria The criteria used to select the current contents of collLabReports.
	 */
	private $lastLabReportCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseVisit object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [patient_id] column value.
	 * 
	 * @return     int
	 */
	public function getPatientId()
	{
		return $this->patient_id;
	}

	/**
	 * Get the [doctor_id] column value.
	 * 
	 * @return     int
	 */
	public function getDoctorId()
	{
		return $this->doctor_id;
	}

	/**
	 * Get the [ward_bed_id] column value.
	 * 
	 * @return     int
	 */
	public function getWardBedId()
	{
		return $this->ward_bed_id;
	}

	/**
	 * Get the [ward_doc_id] column value.
	 * 
	 * @return     int
	 */
	public function getWardDocId()
	{
		return $this->ward_doc_id;
	}

	/**
	 * Get the [visit_type] column value.
	 * 
	 * @return     string
	 */
	public function getVisitType()
	{
		return $this->visit_type;
	}

	/**
	 * Get the [medicine] column value.
	 * 
	 * @return     string
	 */
	public function getMedicine()
	{
		return $this->medicine;
	}

	/**
	 * Get the [bp] column value.
	 * 
	 * @return     string
	 */
	public function getBp()
	{
		return $this->bp;
	}

	/**
	 * Get the [temp] column value.
	 * 
	 * @return     string
	 */
	public function getTemp()
	{
		return $this->temp;
	}

	/**
	 * Get the [pulse] column value.
	 * 
	 * @return     string
	 */
	public function getPulse()
	{
		return $this->pulse;
	}

	/**
	 * Get the [injection] column value.
	 * 
	 * @return     string
	 */
	public function getInjection()
	{
		return $this->injection;
	}

	/**
	 * Get the [diet] column value.
	 * 
	 * @return     string
	 */
	public function getDiet()
	{
		return $this->diet;
	}

	/**
	 * Get the [description] column value.
	 * 
	 * @return     string
	 */
	public function getDescription()
	{
		return $this->description;
	}

	/**
	 * Get the [time] column value.
	 * 
	 * @return     string
	 */
	public function getTime()
	{
		return $this->time;
	}

	/**
	 * Get the [optionally formatted] temporal [visit_date] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getVisitDate($format = 'Y-m-d')
	{
		if ($this->visit_date === null) {
			return null;
		}


		if ($this->visit_date === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->visit_date);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->visit_date, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [fee] column value.
	 * 
	 * @return     string
	 */
	public function getFee()
	{
		return $this->fee;
	}

	/**
	 * Get the [fee_paid] column value.
	 * 
	 * @return     string
	 */
	public function getFeePaid()
	{
		return $this->fee_paid;
	}

	/**
	 * Get the [status] column value.
	 * 
	 * @return     string
	 */
	public function getStatus()
	{
		return $this->status;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Visit The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = VisitPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [patient_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Visit The current object (for fluent API support)
	 */
	public function setPatientId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->patient_id !== $v) {
			$this->patient_id = $v;
			$this->modifiedColumns[] = VisitPeer::PATIENT_ID;
		}

		if ($this->aPatient !== null && $this->aPatient->getId() !== $v) {
			$this->aPatient = null;
		}

		return $this;
	} // setPatientId()

	/**
	 * Set the value of [doctor_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Visit The current object (for fluent API support)
	 */
	public function setDoctorId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->doctor_id !== $v) {
			$this->doctor_id = $v;
			$this->modifiedColumns[] = VisitPeer::DOCTOR_ID;
		}

		if ($this->aEmployeeRelatedByDoctorId !== null && $this->aEmployeeRelatedByDoctorId->getId() !== $v) {
			$this->aEmployeeRelatedByDoctorId = null;
		}

		return $this;
	} // setDoctorId()

	/**
	 * Set the value of [ward_bed_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Visit The current object (for fluent API support)
	 */
	public function setWardBedId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->ward_bed_id !== $v) {
			$this->ward_bed_id = $v;
			$this->modifiedColumns[] = VisitPeer::WARD_BED_ID;
		}

		if ($this->aWardBed !== null && $this->aWardBed->getId() !== $v) {
			$this->aWardBed = null;
		}

		return $this;
	} // setWardBedId()

	/**
	 * Set the value of [ward_doc_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Visit The current object (for fluent API support)
	 */
	public function setWardDocId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->ward_doc_id !== $v) {
			$this->ward_doc_id = $v;
			$this->modifiedColumns[] = VisitPeer::WARD_DOC_ID;
		}

		if ($this->aEmployeeRelatedByWardDocId !== null && $this->aEmployeeRelatedByWardDocId->getId() !== $v) {
			$this->aEmployeeRelatedByWardDocId = null;
		}

		return $this;
	} // setWardDocId()

	/**
	 * Set the value of [visit_type] column.
	 * 
	 * @param      string $v new value
	 * @return     Visit The current object (for fluent API support)
	 */
	public function setVisitType($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->visit_type !== $v) {
			$this->visit_type = $v;
			$this->modifiedColumns[] = VisitPeer::VISIT_TYPE;
		}

		return $this;
	} // setVisitType()

	/**
	 * Set the value of [medicine] column.
	 * 
	 * @param      string $v new value
	 * @return     Visit The current object (for fluent API support)
	 */
	public function setMedicine($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->medicine !== $v) {
			$this->medicine = $v;
			$this->modifiedColumns[] = VisitPeer::MEDICINE;
		}

		return $this;
	} // setMedicine()

	/**
	 * Set the value of [bp] column.
	 * 
	 * @param      string $v new value
	 * @return     Visit The current object (for fluent API support)
	 */
	public function setBp($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->bp !== $v) {
			$this->bp = $v;
			$this->modifiedColumns[] = VisitPeer::BP;
		}

		return $this;
	} // setBp()

	/**
	 * Set the value of [temp] column.
	 * 
	 * @param      string $v new value
	 * @return     Visit The current object (for fluent API support)
	 */
	public function setTemp($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->temp !== $v) {
			$this->temp = $v;
			$this->modifiedColumns[] = VisitPeer::TEMP;
		}

		return $this;
	} // setTemp()

	/**
	 * Set the value of [pulse] column.
	 * 
	 * @param      string $v new value
	 * @return     Visit The current object (for fluent API support)
	 */
	public function setPulse($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pulse !== $v) {
			$this->pulse = $v;
			$this->modifiedColumns[] = VisitPeer::PULSE;
		}

		return $this;
	} // setPulse()

	/**
	 * Set the value of [injection] column.
	 * 
	 * @param      string $v new value
	 * @return     Visit The current object (for fluent API support)
	 */
	public function setInjection($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->injection !== $v) {
			$this->injection = $v;
			$this->modifiedColumns[] = VisitPeer::INJECTION;
		}

		return $this;
	} // setInjection()

	/**
	 * Set the value of [diet] column.
	 * 
	 * @param      string $v new value
	 * @return     Visit The current object (for fluent API support)
	 */
	public function setDiet($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->diet !== $v) {
			$this->diet = $v;
			$this->modifiedColumns[] = VisitPeer::DIET;
		}

		return $this;
	} // setDiet()

	/**
	 * Set the value of [description] column.
	 * 
	 * @param      string $v new value
	 * @return     Visit The current object (for fluent API support)
	 */
	public function setDescription($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->description !== $v) {
			$this->description = $v;
			$this->modifiedColumns[] = VisitPeer::DESCRIPTION;
		}

		return $this;
	} // setDescription()

	/**
	 * Set the value of [time] column.
	 * 
	 * @param      string $v new value
	 * @return     Visit The current object (for fluent API support)
	 */
	public function setTime($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->time !== $v) {
			$this->time = $v;
			$this->modifiedColumns[] = VisitPeer::TIME;
		}

		return $this;
	} // setTime()

	/**
	 * Sets the value of [visit_date] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Visit The current object (for fluent API support)
	 */
	public function setVisitDate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->visit_date !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->visit_date !== null && $tmpDt = new DateTime($this->visit_date)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->visit_date = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = VisitPeer::VISIT_DATE;
			}
		} // if either are not null

		return $this;
	} // setVisitDate()

	/**
	 * Set the value of [fee] column.
	 * 
	 * @param      string $v new value
	 * @return     Visit The current object (for fluent API support)
	 */
	public function setFee($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fee !== $v) {
			$this->fee = $v;
			$this->modifiedColumns[] = VisitPeer::FEE;
		}

		return $this;
	} // setFee()

	/**
	 * Set the value of [fee_paid] column.
	 * 
	 * @param      string $v new value
	 * @return     Visit The current object (for fluent API support)
	 */
	public function setFeePaid($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fee_paid !== $v) {
			$this->fee_paid = $v;
			$this->modifiedColumns[] = VisitPeer::FEE_PAID;
		}

		return $this;
	} // setFeePaid()

	/**
	 * Set the value of [status] column.
	 * 
	 * @param      string $v new value
	 * @return     Visit The current object (for fluent API support)
	 */
	public function setStatus($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->status !== $v) {
			$this->status = $v;
			$this->modifiedColumns[] = VisitPeer::STATUS;
		}

		return $this;
	} // setStatus()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Visit The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = VisitPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Visit The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = VisitPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->patient_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->doctor_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->ward_bed_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->ward_doc_id = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->visit_type = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->medicine = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->bp = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->temp = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->pulse = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->injection = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->diet = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->description = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->time = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->visit_date = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->fee = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->fee_paid = ($row[$startcol + 16] !== null) ? (string) $row[$startcol + 16] : null;
			$this->status = ($row[$startcol + 17] !== null) ? (string) $row[$startcol + 17] : null;
			$this->created_at = ($row[$startcol + 18] !== null) ? (string) $row[$startcol + 18] : null;
			$this->updated_at = ($row[$startcol + 19] !== null) ? (string) $row[$startcol + 19] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 20; // 20 = VisitPeer::NUM_COLUMNS - VisitPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Visit object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aPatient !== null && $this->patient_id !== $this->aPatient->getId()) {
			$this->aPatient = null;
		}
		if ($this->aEmployeeRelatedByDoctorId !== null && $this->doctor_id !== $this->aEmployeeRelatedByDoctorId->getId()) {
			$this->aEmployeeRelatedByDoctorId = null;
		}
		if ($this->aWardBed !== null && $this->ward_bed_id !== $this->aWardBed->getId()) {
			$this->aWardBed = null;
		}
		if ($this->aEmployeeRelatedByWardDocId !== null && $this->ward_doc_id !== $this->aEmployeeRelatedByWardDocId->getId()) {
			$this->aEmployeeRelatedByWardDocId = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(VisitPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = VisitPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aPatient = null;
			$this->aEmployeeRelatedByDoctorId = null;
			$this->aWardBed = null;
			$this->aEmployeeRelatedByWardDocId = null;
			$this->collLabReports = null;
			$this->lastLabReportCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseVisit:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(VisitPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			VisitPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseVisit:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseVisit:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(VisitPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

    if ($this->isModified() && !$this->isColumnModified(VisitPeer::UPDATED_AT))
    {
      $this->setUpdatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(VisitPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseVisit:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			VisitPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPatient !== null) {
				if ($this->aPatient->isModified() || $this->aPatient->isNew()) {
					$affectedRows += $this->aPatient->save($con);
				}
				$this->setPatient($this->aPatient);
			}

			if ($this->aEmployeeRelatedByDoctorId !== null) {
				if ($this->aEmployeeRelatedByDoctorId->isModified() || $this->aEmployeeRelatedByDoctorId->isNew()) {
					$affectedRows += $this->aEmployeeRelatedByDoctorId->save($con);
				}
				$this->setEmployeeRelatedByDoctorId($this->aEmployeeRelatedByDoctorId);
			}

			if ($this->aWardBed !== null) {
				if ($this->aWardBed->isModified() || $this->aWardBed->isNew()) {
					$affectedRows += $this->aWardBed->save($con);
				}
				$this->setWardBed($this->aWardBed);
			}

			if ($this->aEmployeeRelatedByWardDocId !== null) {
				if ($this->aEmployeeRelatedByWardDocId->isModified() || $this->aEmployeeRelatedByWardDocId->isNew()) {
					$affectedRows += $this->aEmployeeRelatedByWardDocId->save($con);
				}
				$this->setEmployeeRelatedByWardDocId($this->aEmployeeRelatedByWardDocId);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = VisitPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = VisitPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += VisitPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collLabReports !== null) {
				foreach ($this->collLabReports as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPatient !== null) {
				if (!$this->aPatient->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPatient->getValidationFailures());
				}
			}

			if ($this->aEmployeeRelatedByDoctorId !== null) {
				if (!$this->aEmployeeRelatedByDoctorId->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aEmployeeRelatedByDoctorId->getValidationFailures());
				}
			}

			if ($this->aWardBed !== null) {
				if (!$this->aWardBed->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aWardBed->getValidationFailures());
				}
			}

			if ($this->aEmployeeRelatedByWardDocId !== null) {
				if (!$this->aEmployeeRelatedByWardDocId->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aEmployeeRelatedByWardDocId->getValidationFailures());
				}
			}


			if (($retval = VisitPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collLabReports !== null) {
					foreach ($this->collLabReports as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = VisitPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getPatientId();
				break;
			case 2:
				return $this->getDoctorId();
				break;
			case 3:
				return $this->getWardBedId();
				break;
			case 4:
				return $this->getWardDocId();
				break;
			case 5:
				return $this->getVisitType();
				break;
			case 6:
				return $this->getMedicine();
				break;
			case 7:
				return $this->getBp();
				break;
			case 8:
				return $this->getTemp();
				break;
			case 9:
				return $this->getPulse();
				break;
			case 10:
				return $this->getInjection();
				break;
			case 11:
				return $this->getDiet();
				break;
			case 12:
				return $this->getDescription();
				break;
			case 13:
				return $this->getTime();
				break;
			case 14:
				return $this->getVisitDate();
				break;
			case 15:
				return $this->getFee();
				break;
			case 16:
				return $this->getFeePaid();
				break;
			case 17:
				return $this->getStatus();
				break;
			case 18:
				return $this->getCreatedAt();
				break;
			case 19:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = VisitPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getPatientId(),
			$keys[2] => $this->getDoctorId(),
			$keys[3] => $this->getWardBedId(),
			$keys[4] => $this->getWardDocId(),
			$keys[5] => $this->getVisitType(),
			$keys[6] => $this->getMedicine(),
			$keys[7] => $this->getBp(),
			$keys[8] => $this->getTemp(),
			$keys[9] => $this->getPulse(),
			$keys[10] => $this->getInjection(),
			$keys[11] => $this->getDiet(),
			$keys[12] => $this->getDescription(),
			$keys[13] => $this->getTime(),
			$keys[14] => $this->getVisitDate(),
			$keys[15] => $this->getFee(),
			$keys[16] => $this->getFeePaid(),
			$keys[17] => $this->getStatus(),
			$keys[18] => $this->getCreatedAt(),
			$keys[19] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = VisitPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setPatientId($value);
				break;
			case 2:
				$this->setDoctorId($value);
				break;
			case 3:
				$this->setWardBedId($value);
				break;
			case 4:
				$this->setWardDocId($value);
				break;
			case 5:
				$this->setVisitType($value);
				break;
			case 6:
				$this->setMedicine($value);
				break;
			case 7:
				$this->setBp($value);
				break;
			case 8:
				$this->setTemp($value);
				break;
			case 9:
				$this->setPulse($value);
				break;
			case 10:
				$this->setInjection($value);
				break;
			case 11:
				$this->setDiet($value);
				break;
			case 12:
				$this->setDescription($value);
				break;
			case 13:
				$this->setTime($value);
				break;
			case 14:
				$this->setVisitDate($value);
				break;
			case 15:
				$this->setFee($value);
				break;
			case 16:
				$this->setFeePaid($value);
				break;
			case 17:
				$this->setStatus($value);
				break;
			case 18:
				$this->setCreatedAt($value);
				break;
			case 19:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = VisitPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setPatientId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setDoctorId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setWardBedId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setWardDocId($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setVisitType($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setMedicine($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setBp($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setTemp($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setPulse($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setInjection($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setDiet($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setDescription($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setTime($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setVisitDate($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setFee($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setFeePaid($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setStatus($arr[$keys[17]]);
		if (array_key_exists($keys[18], $arr)) $this->setCreatedAt($arr[$keys[18]]);
		if (array_key_exists($keys[19], $arr)) $this->setUpdatedAt($arr[$keys[19]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(VisitPeer::DATABASE_NAME);

		if ($this->isColumnModified(VisitPeer::ID)) $criteria->add(VisitPeer::ID, $this->id);
		if ($this->isColumnModified(VisitPeer::PATIENT_ID)) $criteria->add(VisitPeer::PATIENT_ID, $this->patient_id);
		if ($this->isColumnModified(VisitPeer::DOCTOR_ID)) $criteria->add(VisitPeer::DOCTOR_ID, $this->doctor_id);
		if ($this->isColumnModified(VisitPeer::WARD_BED_ID)) $criteria->add(VisitPeer::WARD_BED_ID, $this->ward_bed_id);
		if ($this->isColumnModified(VisitPeer::WARD_DOC_ID)) $criteria->add(VisitPeer::WARD_DOC_ID, $this->ward_doc_id);
		if ($this->isColumnModified(VisitPeer::VISIT_TYPE)) $criteria->add(VisitPeer::VISIT_TYPE, $this->visit_type);
		if ($this->isColumnModified(VisitPeer::MEDICINE)) $criteria->add(VisitPeer::MEDICINE, $this->medicine);
		if ($this->isColumnModified(VisitPeer::BP)) $criteria->add(VisitPeer::BP, $this->bp);
		if ($this->isColumnModified(VisitPeer::TEMP)) $criteria->add(VisitPeer::TEMP, $this->temp);
		if ($this->isColumnModified(VisitPeer::PULSE)) $criteria->add(VisitPeer::PULSE, $this->pulse);
		if ($this->isColumnModified(VisitPeer::INJECTION)) $criteria->add(VisitPeer::INJECTION, $this->injection);
		if ($this->isColumnModified(VisitPeer::DIET)) $criteria->add(VisitPeer::DIET, $this->diet);
		if ($this->isColumnModified(VisitPeer::DESCRIPTION)) $criteria->add(VisitPeer::DESCRIPTION, $this->description);
		if ($this->isColumnModified(VisitPeer::TIME)) $criteria->add(VisitPeer::TIME, $this->time);
		if ($this->isColumnModified(VisitPeer::VISIT_DATE)) $criteria->add(VisitPeer::VISIT_DATE, $this->visit_date);
		if ($this->isColumnModified(VisitPeer::FEE)) $criteria->add(VisitPeer::FEE, $this->fee);
		if ($this->isColumnModified(VisitPeer::FEE_PAID)) $criteria->add(VisitPeer::FEE_PAID, $this->fee_paid);
		if ($this->isColumnModified(VisitPeer::STATUS)) $criteria->add(VisitPeer::STATUS, $this->status);
		if ($this->isColumnModified(VisitPeer::CREATED_AT)) $criteria->add(VisitPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(VisitPeer::UPDATED_AT)) $criteria->add(VisitPeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(VisitPeer::DATABASE_NAME);

		$criteria->add(VisitPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Visit (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setPatientId($this->patient_id);

		$copyObj->setDoctorId($this->doctor_id);

		$copyObj->setWardBedId($this->ward_bed_id);

		$copyObj->setWardDocId($this->ward_doc_id);

		$copyObj->setVisitType($this->visit_type);

		$copyObj->setMedicine($this->medicine);

		$copyObj->setBp($this->bp);

		$copyObj->setTemp($this->temp);

		$copyObj->setPulse($this->pulse);

		$copyObj->setInjection($this->injection);

		$copyObj->setDiet($this->diet);

		$copyObj->setDescription($this->description);

		$copyObj->setTime($this->time);

		$copyObj->setVisitDate($this->visit_date);

		$copyObj->setFee($this->fee);

		$copyObj->setFeePaid($this->fee_paid);

		$copyObj->setStatus($this->status);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getLabReports() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addLabReport($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Visit Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     VisitPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new VisitPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Patient object.
	 *
	 * @param      Patient $v
	 * @return     Visit The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPatient(Patient $v = null)
	{
		if ($v === null) {
			$this->setPatientId(NULL);
		} else {
			$this->setPatientId($v->getId());
		}

		$this->aPatient = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Patient object, it will not be re-added.
		if ($v !== null) {
			$v->addVisit($this);
		}

		return $this;
	}


	/**
	 * Get the associated Patient object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Patient The associated Patient object.
	 * @throws     PropelException
	 */
	public function getPatient(PropelPDO $con = null)
	{
		if ($this->aPatient === null && ($this->patient_id !== null)) {
			$c = new Criteria(PatientPeer::DATABASE_NAME);
			$c->add(PatientPeer::ID, $this->patient_id);
			$this->aPatient = PatientPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPatient->addVisits($this);
			 */
		}
		return $this->aPatient;
	}

	/**
	 * Declares an association between this object and a Employee object.
	 *
	 * @param      Employee $v
	 * @return     Visit The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setEmployeeRelatedByDoctorId(Employee $v = null)
	{
		if ($v === null) {
			$this->setDoctorId(NULL);
		} else {
			$this->setDoctorId($v->getId());
		}

		$this->aEmployeeRelatedByDoctorId = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Employee object, it will not be re-added.
		if ($v !== null) {
			$v->addVisitRelatedByDoctorId($this);
		}

		return $this;
	}


	/**
	 * Get the associated Employee object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Employee The associated Employee object.
	 * @throws     PropelException
	 */
	public function getEmployeeRelatedByDoctorId(PropelPDO $con = null)
	{
		if ($this->aEmployeeRelatedByDoctorId === null && ($this->doctor_id !== null)) {
			$c = new Criteria(EmployeePeer::DATABASE_NAME);
			$c->add(EmployeePeer::ID, $this->doctor_id);
			$this->aEmployeeRelatedByDoctorId = EmployeePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aEmployeeRelatedByDoctorId->addVisitsRelatedByDoctorId($this);
			 */
		}
		return $this->aEmployeeRelatedByDoctorId;
	}

	/**
	 * Declares an association between this object and a WardBed object.
	 *
	 * @param      WardBed $v
	 * @return     Visit The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setWardBed(WardBed $v = null)
	{
		if ($v === null) {
			$this->setWardBedId(NULL);
		} else {
			$this->setWardBedId($v->getId());
		}

		$this->aWardBed = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the WardBed object, it will not be re-added.
		if ($v !== null) {
			$v->addVisit($this);
		}

		return $this;
	}


	/**
	 * Get the associated WardBed object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     WardBed The associated WardBed object.
	 * @throws     PropelException
	 */
	public function getWardBed(PropelPDO $con = null)
	{
		if ($this->aWardBed === null && ($this->ward_bed_id !== null)) {
			$c = new Criteria(WardBedPeer::DATABASE_NAME);
			$c->add(WardBedPeer::ID, $this->ward_bed_id);
			$this->aWardBed = WardBedPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aWardBed->addVisits($this);
			 */
		}
		return $this->aWardBed;
	}

	/**
	 * Declares an association between this object and a Employee object.
	 *
	 * @param      Employee $v
	 * @return     Visit The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setEmployeeRelatedByWardDocId(Employee $v = null)
	{
		if ($v === null) {
			$this->setWardDocId(NULL);
		} else {
			$this->setWardDocId($v->getId());
		}

		$this->aEmployeeRelatedByWardDocId = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Employee object, it will not be re-added.
		if ($v !== null) {
			$v->addVisitRelatedByWardDocId($this);
		}

		return $this;
	}


	/**
	 * Get the associated Employee object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Employee The associated Employee object.
	 * @throws     PropelException
	 */
	public function getEmployeeRelatedByWardDocId(PropelPDO $con = null)
	{
		if ($this->aEmployeeRelatedByWardDocId === null && ($this->ward_doc_id !== null)) {
			$c = new Criteria(EmployeePeer::DATABASE_NAME);
			$c->add(EmployeePeer::ID, $this->ward_doc_id);
			$this->aEmployeeRelatedByWardDocId = EmployeePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aEmployeeRelatedByWardDocId->addVisitsRelatedByWardDocId($this);
			 */
		}
		return $this->aEmployeeRelatedByWardDocId;
	}

	/**
	 * Clears out the collLabReports collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addLabReports()
	 */
	public function clearLabReports()
	{
		$this->collLabReports = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collLabReports collection (array).
	 *
	 * By default this just sets the collLabReports collection to an empty array (like clearcollLabReports());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initLabReports()
	{
		$this->collLabReports = array();
	}

	/**
	 * Gets an array of LabReport objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Visit has previously been saved, it will retrieve
	 * related LabReports from storage. If this Visit is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array LabReport[]
	 * @throws     PropelException
	 */
	public function getLabReports($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VisitPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collLabReports === null) {
			if ($this->isNew()) {
			   $this->collLabReports = array();
			} else {

				$criteria->add(LabReportPeer::VISIT_ID, $this->id);

				LabReportPeer::addSelectColumns($criteria);
				$this->collLabReports = LabReportPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(LabReportPeer::VISIT_ID, $this->id);

				LabReportPeer::addSelectColumns($criteria);
				if (!isset($this->lastLabReportCriteria) || !$this->lastLabReportCriteria->equals($criteria)) {
					$this->collLabReports = LabReportPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastLabReportCriteria = $criteria;
		return $this->collLabReports;
	}

	/**
	 * Returns the number of related LabReport objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related LabReport objects.
	 * @throws     PropelException
	 */
	public function countLabReports(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VisitPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collLabReports === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(LabReportPeer::VISIT_ID, $this->id);

				$count = LabReportPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(LabReportPeer::VISIT_ID, $this->id);

				if (!isset($this->lastLabReportCriteria) || !$this->lastLabReportCriteria->equals($criteria)) {
					$count = LabReportPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collLabReports);
				}
			} else {
				$count = count($this->collLabReports);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a LabReport object to this object
	 * through the LabReport foreign key attribute.
	 *
	 * @param      LabReport $l LabReport
	 * @return     void
	 * @throws     PropelException
	 */
	public function addLabReport(LabReport $l)
	{
		if ($this->collLabReports === null) {
			$this->initLabReports();
		}
		if (!in_array($l, $this->collLabReports, true)) { // only add it if the **same** object is not already associated
			array_push($this->collLabReports, $l);
			$l->setVisit($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Visit is new, it will return
	 * an empty collection; or if this Visit has previously
	 * been saved, it will retrieve related LabReports from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Visit.
	 */
	public function getLabReportsJoinPatient($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VisitPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collLabReports === null) {
			if ($this->isNew()) {
				$this->collLabReports = array();
			} else {

				$criteria->add(LabReportPeer::VISIT_ID, $this->id);

				$this->collLabReports = LabReportPeer::doSelectJoinPatient($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(LabReportPeer::VISIT_ID, $this->id);

			if (!isset($this->lastLabReportCriteria) || !$this->lastLabReportCriteria->equals($criteria)) {
				$this->collLabReports = LabReportPeer::doSelectJoinPatient($criteria, $con, $join_behavior);
			}
		}
		$this->lastLabReportCriteria = $criteria;

		return $this->collLabReports;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Visit is new, it will return
	 * an empty collection; or if this Visit has previously
	 * been saved, it will retrieve related LabReports from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Visit.
	 */
	public function getLabReportsJoinLabTest($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VisitPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collLabReports === null) {
			if ($this->isNew()) {
				$this->collLabReports = array();
			} else {

				$criteria->add(LabReportPeer::VISIT_ID, $this->id);

				$this->collLabReports = LabReportPeer::doSelectJoinLabTest($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(LabReportPeer::VISIT_ID, $this->id);

			if (!isset($this->lastLabReportCriteria) || !$this->lastLabReportCriteria->equals($criteria)) {
				$this->collLabReports = LabReportPeer::doSelectJoinLabTest($criteria, $con, $join_behavior);
			}
		}
		$this->lastLabReportCriteria = $criteria;

		return $this->collLabReports;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collLabReports) {
				foreach ((array) $this->collLabReports as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collLabReports = null;
			$this->aPatient = null;
			$this->aEmployeeRelatedByDoctorId = null;
			$this->aWardBed = null;
			$this->aEmployeeRelatedByWardDocId = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseVisit:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseVisit::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseVisit
