<?php

/**
 * Base class that represents a row from the 'patient' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 06/17/11 08:02:42
 *
 * @package    lib.model.om
 */
abstract class BasePatient extends BaseObject  implements Persistent {


  const PEER = 'PatientPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        PatientPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the id_number field.
	 * @var        string
	 */
	protected $id_number;

	/**
	 * The value for the cnic field.
	 * @var        string
	 */
	protected $cnic;

	/**
	 * The value for the username field.
	 * @var        string
	 */
	protected $username;

	/**
	 * The value for the password field.
	 * @var        string
	 */
	protected $password;

	/**
	 * The value for the name field.
	 * @var        string
	 */
	protected $name;

	/**
	 * The value for the father_name field.
	 * @var        string
	 */
	protected $father_name;

	/**
	 * The value for the dob field.
	 * @var        string
	 */
	protected $dob;

	/**
	 * The value for the gender field.
	 * @var        string
	 */
	protected $gender;

	/**
	 * The value for the address field.
	 * @var        string
	 */
	protected $address;

	/**
	 * The value for the contact_res field.
	 * @var        string
	 */
	protected $contact_res;

	/**
	 * The value for the contact_cell field.
	 * @var        string
	 */
	protected $contact_cell;

	/**
	 * The value for the emergency_contact field.
	 * @var        string
	 */
	protected $emergency_contact;

	/**
	 * The value for the email field.
	 * @var        string
	 */
	protected $email;

	/**
	 * The value for the blood_group field.
	 * @var        string
	 */
	protected $blood_group;

	/**
	 * The value for the disease field.
	 * @var        string
	 */
	protected $disease;

	/**
	 * The value for the allergy field.
	 * @var        string
	 */
	protected $allergy;

	/**
	 * The value for the drug_allergy field.
	 * @var        string
	 */
	protected $drug_allergy;

	/**
	 * The value for the status field.
	 * @var        string
	 */
	protected $status;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        array LabReport[] Collection to store aggregation of LabReport objects.
	 */
	protected $collLabReports;

	/**
	 * @var        Criteria The criteria used to select the current contents of collLabReports.
	 */
	private $lastLabReportCriteria = null;

	/**
	 * @var        array Visit[] Collection to store aggregation of Visit objects.
	 */
	protected $collVisits;

	/**
	 * @var        Criteria The criteria used to select the current contents of collVisits.
	 */
	private $lastVisitCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BasePatient object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [id_number] column value.
	 * 
	 * @return     string
	 */
	public function getIdNumber()
	{
		return $this->id_number;
	}

	/**
	 * Get the [cnic] column value.
	 * 
	 * @return     string
	 */
	public function getCnic()
	{
		return $this->cnic;
	}

	/**
	 * Get the [username] column value.
	 * 
	 * @return     string
	 */
	public function getUsername()
	{
		return $this->username;
	}

	/**
	 * Get the [password] column value.
	 * 
	 * @return     string
	 */
	public function getPassword()
	{
		return $this->password;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Get the [father_name] column value.
	 * 
	 * @return     string
	 */
	public function getFatherName()
	{
		return $this->father_name;
	}

	/**
	 * Get the [optionally formatted] temporal [dob] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDob($format = 'Y-m-d')
	{
		if ($this->dob === null) {
			return null;
		}


		if ($this->dob === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->dob);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->dob, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [gender] column value.
	 * 
	 * @return     string
	 */
	public function getGender()
	{
		return $this->gender;
	}

	/**
	 * Get the [address] column value.
	 * 
	 * @return     string
	 */
	public function getAddress()
	{
		return $this->address;
	}

	/**
	 * Get the [contact_res] column value.
	 * 
	 * @return     string
	 */
	public function getContactRes()
	{
		return $this->contact_res;
	}

	/**
	 * Get the [contact_cell] column value.
	 * 
	 * @return     string
	 */
	public function getContactCell()
	{
		return $this->contact_cell;
	}

	/**
	 * Get the [emergency_contact] column value.
	 * 
	 * @return     string
	 */
	public function getEmergencyContact()
	{
		return $this->emergency_contact;
	}

	/**
	 * Get the [email] column value.
	 * 
	 * @return     string
	 */
	public function getEmail()
	{
		return $this->email;
	}

	/**
	 * Get the [blood_group] column value.
	 * 
	 * @return     string
	 */
	public function getBloodGroup()
	{
		return $this->blood_group;
	}

	/**
	 * Get the [disease] column value.
	 * 
	 * @return     string
	 */
	public function getDisease()
	{
		return $this->disease;
	}

	/**
	 * Get the [allergy] column value.
	 * 
	 * @return     string
	 */
	public function getAllergy()
	{
		return $this->allergy;
	}

	/**
	 * Get the [drug_allergy] column value.
	 * 
	 * @return     string
	 */
	public function getDrugAllergy()
	{
		return $this->drug_allergy;
	}

	/**
	 * Get the [status] column value.
	 * 
	 * @return     string
	 */
	public function getStatus()
	{
		return $this->status;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Patient The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = PatientPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [id_number] column.
	 * 
	 * @param      string $v new value
	 * @return     Patient The current object (for fluent API support)
	 */
	public function setIdNumber($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->id_number !== $v) {
			$this->id_number = $v;
			$this->modifiedColumns[] = PatientPeer::ID_NUMBER;
		}

		return $this;
	} // setIdNumber()

	/**
	 * Set the value of [cnic] column.
	 * 
	 * @param      string $v new value
	 * @return     Patient The current object (for fluent API support)
	 */
	public function setCnic($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->cnic !== $v) {
			$this->cnic = $v;
			$this->modifiedColumns[] = PatientPeer::CNIC;
		}

		return $this;
	} // setCnic()

	/**
	 * Set the value of [username] column.
	 * 
	 * @param      string $v new value
	 * @return     Patient The current object (for fluent API support)
	 */
	public function setUsername($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->username !== $v) {
			$this->username = $v;
			$this->modifiedColumns[] = PatientPeer::USERNAME;
		}

		return $this;
	} // setUsername()

	/**
	 * Set the value of [password] column.
	 * 
	 * @param      string $v new value
	 * @return     Patient The current object (for fluent API support)
	 */
	public function setPassword($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->password !== $v) {
			$this->password = $v;
			$this->modifiedColumns[] = PatientPeer::PASSWORD;
		}

		return $this;
	} // setPassword()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     Patient The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v) {
			$this->name = $v;
			$this->modifiedColumns[] = PatientPeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Set the value of [father_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Patient The current object (for fluent API support)
	 */
	public function setFatherName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->father_name !== $v) {
			$this->father_name = $v;
			$this->modifiedColumns[] = PatientPeer::FATHER_NAME;
		}

		return $this;
	} // setFatherName()

	/**
	 * Sets the value of [dob] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Patient The current object (for fluent API support)
	 */
	public function setDob($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->dob !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->dob !== null && $tmpDt = new DateTime($this->dob)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->dob = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = PatientPeer::DOB;
			}
		} // if either are not null

		return $this;
	} // setDob()

	/**
	 * Set the value of [gender] column.
	 * 
	 * @param      string $v new value
	 * @return     Patient The current object (for fluent API support)
	 */
	public function setGender($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->gender !== $v) {
			$this->gender = $v;
			$this->modifiedColumns[] = PatientPeer::GENDER;
		}

		return $this;
	} // setGender()

	/**
	 * Set the value of [address] column.
	 * 
	 * @param      string $v new value
	 * @return     Patient The current object (for fluent API support)
	 */
	public function setAddress($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->address !== $v) {
			$this->address = $v;
			$this->modifiedColumns[] = PatientPeer::ADDRESS;
		}

		return $this;
	} // setAddress()

	/**
	 * Set the value of [contact_res] column.
	 * 
	 * @param      string $v new value
	 * @return     Patient The current object (for fluent API support)
	 */
	public function setContactRes($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->contact_res !== $v) {
			$this->contact_res = $v;
			$this->modifiedColumns[] = PatientPeer::CONTACT_RES;
		}

		return $this;
	} // setContactRes()

	/**
	 * Set the value of [contact_cell] column.
	 * 
	 * @param      string $v new value
	 * @return     Patient The current object (for fluent API support)
	 */
	public function setContactCell($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->contact_cell !== $v) {
			$this->contact_cell = $v;
			$this->modifiedColumns[] = PatientPeer::CONTACT_CELL;
		}

		return $this;
	} // setContactCell()

	/**
	 * Set the value of [emergency_contact] column.
	 * 
	 * @param      string $v new value
	 * @return     Patient The current object (for fluent API support)
	 */
	public function setEmergencyContact($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->emergency_contact !== $v) {
			$this->emergency_contact = $v;
			$this->modifiedColumns[] = PatientPeer::EMERGENCY_CONTACT;
		}

		return $this;
	} // setEmergencyContact()

	/**
	 * Set the value of [email] column.
	 * 
	 * @param      string $v new value
	 * @return     Patient The current object (for fluent API support)
	 */
	public function setEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->email !== $v) {
			$this->email = $v;
			$this->modifiedColumns[] = PatientPeer::EMAIL;
		}

		return $this;
	} // setEmail()

	/**
	 * Set the value of [blood_group] column.
	 * 
	 * @param      string $v new value
	 * @return     Patient The current object (for fluent API support)
	 */
	public function setBloodGroup($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->blood_group !== $v) {
			$this->blood_group = $v;
			$this->modifiedColumns[] = PatientPeer::BLOOD_GROUP;
		}

		return $this;
	} // setBloodGroup()

	/**
	 * Set the value of [disease] column.
	 * 
	 * @param      string $v new value
	 * @return     Patient The current object (for fluent API support)
	 */
	public function setDisease($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->disease !== $v) {
			$this->disease = $v;
			$this->modifiedColumns[] = PatientPeer::DISEASE;
		}

		return $this;
	} // setDisease()

	/**
	 * Set the value of [allergy] column.
	 * 
	 * @param      string $v new value
	 * @return     Patient The current object (for fluent API support)
	 */
	public function setAllergy($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->allergy !== $v) {
			$this->allergy = $v;
			$this->modifiedColumns[] = PatientPeer::ALLERGY;
		}

		return $this;
	} // setAllergy()

	/**
	 * Set the value of [drug_allergy] column.
	 * 
	 * @param      string $v new value
	 * @return     Patient The current object (for fluent API support)
	 */
	public function setDrugAllergy($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->drug_allergy !== $v) {
			$this->drug_allergy = $v;
			$this->modifiedColumns[] = PatientPeer::DRUG_ALLERGY;
		}

		return $this;
	} // setDrugAllergy()

	/**
	 * Set the value of [status] column.
	 * 
	 * @param      string $v new value
	 * @return     Patient The current object (for fluent API support)
	 */
	public function setStatus($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->status !== $v) {
			$this->status = $v;
			$this->modifiedColumns[] = PatientPeer::STATUS;
		}

		return $this;
	} // setStatus()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Patient The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = PatientPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Patient The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = PatientPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->id_number = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->cnic = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->username = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->password = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->name = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->father_name = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->dob = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->gender = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->address = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->contact_res = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->contact_cell = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->emergency_contact = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->email = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->blood_group = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->disease = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->allergy = ($row[$startcol + 16] !== null) ? (string) $row[$startcol + 16] : null;
			$this->drug_allergy = ($row[$startcol + 17] !== null) ? (string) $row[$startcol + 17] : null;
			$this->status = ($row[$startcol + 18] !== null) ? (string) $row[$startcol + 18] : null;
			$this->created_at = ($row[$startcol + 19] !== null) ? (string) $row[$startcol + 19] : null;
			$this->updated_at = ($row[$startcol + 20] !== null) ? (string) $row[$startcol + 20] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 21; // 21 = PatientPeer::NUM_COLUMNS - PatientPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Patient object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PatientPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = PatientPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collLabReports = null;
			$this->lastLabReportCriteria = null;

			$this->collVisits = null;
			$this->lastVisitCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BasePatient:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PatientPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			PatientPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BasePatient:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BasePatient:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(PatientPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

    if ($this->isModified() && !$this->isColumnModified(PatientPeer::UPDATED_AT))
    {
      $this->setUpdatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PatientPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BasePatient:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			PatientPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = PatientPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = PatientPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += PatientPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collLabReports !== null) {
				foreach ($this->collLabReports as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collVisits !== null) {
				foreach ($this->collVisits as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = PatientPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collLabReports !== null) {
					foreach ($this->collLabReports as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collVisits !== null) {
					foreach ($this->collVisits as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PatientPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getIdNumber();
				break;
			case 2:
				return $this->getCnic();
				break;
			case 3:
				return $this->getUsername();
				break;
			case 4:
				return $this->getPassword();
				break;
			case 5:
				return $this->getName();
				break;
			case 6:
				return $this->getFatherName();
				break;
			case 7:
				return $this->getDob();
				break;
			case 8:
				return $this->getGender();
				break;
			case 9:
				return $this->getAddress();
				break;
			case 10:
				return $this->getContactRes();
				break;
			case 11:
				return $this->getContactCell();
				break;
			case 12:
				return $this->getEmergencyContact();
				break;
			case 13:
				return $this->getEmail();
				break;
			case 14:
				return $this->getBloodGroup();
				break;
			case 15:
				return $this->getDisease();
				break;
			case 16:
				return $this->getAllergy();
				break;
			case 17:
				return $this->getDrugAllergy();
				break;
			case 18:
				return $this->getStatus();
				break;
			case 19:
				return $this->getCreatedAt();
				break;
			case 20:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = PatientPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getIdNumber(),
			$keys[2] => $this->getCnic(),
			$keys[3] => $this->getUsername(),
			$keys[4] => $this->getPassword(),
			$keys[5] => $this->getName(),
			$keys[6] => $this->getFatherName(),
			$keys[7] => $this->getDob(),
			$keys[8] => $this->getGender(),
			$keys[9] => $this->getAddress(),
			$keys[10] => $this->getContactRes(),
			$keys[11] => $this->getContactCell(),
			$keys[12] => $this->getEmergencyContact(),
			$keys[13] => $this->getEmail(),
			$keys[14] => $this->getBloodGroup(),
			$keys[15] => $this->getDisease(),
			$keys[16] => $this->getAllergy(),
			$keys[17] => $this->getDrugAllergy(),
			$keys[18] => $this->getStatus(),
			$keys[19] => $this->getCreatedAt(),
			$keys[20] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PatientPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setIdNumber($value);
				break;
			case 2:
				$this->setCnic($value);
				break;
			case 3:
				$this->setUsername($value);
				break;
			case 4:
				$this->setPassword($value);
				break;
			case 5:
				$this->setName($value);
				break;
			case 6:
				$this->setFatherName($value);
				break;
			case 7:
				$this->setDob($value);
				break;
			case 8:
				$this->setGender($value);
				break;
			case 9:
				$this->setAddress($value);
				break;
			case 10:
				$this->setContactRes($value);
				break;
			case 11:
				$this->setContactCell($value);
				break;
			case 12:
				$this->setEmergencyContact($value);
				break;
			case 13:
				$this->setEmail($value);
				break;
			case 14:
				$this->setBloodGroup($value);
				break;
			case 15:
				$this->setDisease($value);
				break;
			case 16:
				$this->setAllergy($value);
				break;
			case 17:
				$this->setDrugAllergy($value);
				break;
			case 18:
				$this->setStatus($value);
				break;
			case 19:
				$this->setCreatedAt($value);
				break;
			case 20:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = PatientPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setIdNumber($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setCnic($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setUsername($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setPassword($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setName($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setFatherName($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setDob($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setGender($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setAddress($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setContactRes($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setContactCell($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setEmergencyContact($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setEmail($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setBloodGroup($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setDisease($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setAllergy($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setDrugAllergy($arr[$keys[17]]);
		if (array_key_exists($keys[18], $arr)) $this->setStatus($arr[$keys[18]]);
		if (array_key_exists($keys[19], $arr)) $this->setCreatedAt($arr[$keys[19]]);
		if (array_key_exists($keys[20], $arr)) $this->setUpdatedAt($arr[$keys[20]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(PatientPeer::DATABASE_NAME);

		if ($this->isColumnModified(PatientPeer::ID)) $criteria->add(PatientPeer::ID, $this->id);
		if ($this->isColumnModified(PatientPeer::ID_NUMBER)) $criteria->add(PatientPeer::ID_NUMBER, $this->id_number);
		if ($this->isColumnModified(PatientPeer::CNIC)) $criteria->add(PatientPeer::CNIC, $this->cnic);
		if ($this->isColumnModified(PatientPeer::USERNAME)) $criteria->add(PatientPeer::USERNAME, $this->username);
		if ($this->isColumnModified(PatientPeer::PASSWORD)) $criteria->add(PatientPeer::PASSWORD, $this->password);
		if ($this->isColumnModified(PatientPeer::NAME)) $criteria->add(PatientPeer::NAME, $this->name);
		if ($this->isColumnModified(PatientPeer::FATHER_NAME)) $criteria->add(PatientPeer::FATHER_NAME, $this->father_name);
		if ($this->isColumnModified(PatientPeer::DOB)) $criteria->add(PatientPeer::DOB, $this->dob);
		if ($this->isColumnModified(PatientPeer::GENDER)) $criteria->add(PatientPeer::GENDER, $this->gender);
		if ($this->isColumnModified(PatientPeer::ADDRESS)) $criteria->add(PatientPeer::ADDRESS, $this->address);
		if ($this->isColumnModified(PatientPeer::CONTACT_RES)) $criteria->add(PatientPeer::CONTACT_RES, $this->contact_res);
		if ($this->isColumnModified(PatientPeer::CONTACT_CELL)) $criteria->add(PatientPeer::CONTACT_CELL, $this->contact_cell);
		if ($this->isColumnModified(PatientPeer::EMERGENCY_CONTACT)) $criteria->add(PatientPeer::EMERGENCY_CONTACT, $this->emergency_contact);
		if ($this->isColumnModified(PatientPeer::EMAIL)) $criteria->add(PatientPeer::EMAIL, $this->email);
		if ($this->isColumnModified(PatientPeer::BLOOD_GROUP)) $criteria->add(PatientPeer::BLOOD_GROUP, $this->blood_group);
		if ($this->isColumnModified(PatientPeer::DISEASE)) $criteria->add(PatientPeer::DISEASE, $this->disease);
		if ($this->isColumnModified(PatientPeer::ALLERGY)) $criteria->add(PatientPeer::ALLERGY, $this->allergy);
		if ($this->isColumnModified(PatientPeer::DRUG_ALLERGY)) $criteria->add(PatientPeer::DRUG_ALLERGY, $this->drug_allergy);
		if ($this->isColumnModified(PatientPeer::STATUS)) $criteria->add(PatientPeer::STATUS, $this->status);
		if ($this->isColumnModified(PatientPeer::CREATED_AT)) $criteria->add(PatientPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(PatientPeer::UPDATED_AT)) $criteria->add(PatientPeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(PatientPeer::DATABASE_NAME);

		$criteria->add(PatientPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Patient (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setIdNumber($this->id_number);

		$copyObj->setCnic($this->cnic);

		$copyObj->setUsername($this->username);

		$copyObj->setPassword($this->password);

		$copyObj->setName($this->name);

		$copyObj->setFatherName($this->father_name);

		$copyObj->setDob($this->dob);

		$copyObj->setGender($this->gender);

		$copyObj->setAddress($this->address);

		$copyObj->setContactRes($this->contact_res);

		$copyObj->setContactCell($this->contact_cell);

		$copyObj->setEmergencyContact($this->emergency_contact);

		$copyObj->setEmail($this->email);

		$copyObj->setBloodGroup($this->blood_group);

		$copyObj->setDisease($this->disease);

		$copyObj->setAllergy($this->allergy);

		$copyObj->setDrugAllergy($this->drug_allergy);

		$copyObj->setStatus($this->status);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getLabReports() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addLabReport($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getVisits() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addVisit($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Patient Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     PatientPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new PatientPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collLabReports collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addLabReports()
	 */
	public function clearLabReports()
	{
		$this->collLabReports = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collLabReports collection (array).
	 *
	 * By default this just sets the collLabReports collection to an empty array (like clearcollLabReports());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initLabReports()
	{
		$this->collLabReports = array();
	}

	/**
	 * Gets an array of LabReport objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Patient has previously been saved, it will retrieve
	 * related LabReports from storage. If this Patient is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array LabReport[]
	 * @throws     PropelException
	 */
	public function getLabReports($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PatientPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collLabReports === null) {
			if ($this->isNew()) {
			   $this->collLabReports = array();
			} else {

				$criteria->add(LabReportPeer::PATIENT_ID, $this->id);

				LabReportPeer::addSelectColumns($criteria);
				$this->collLabReports = LabReportPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(LabReportPeer::PATIENT_ID, $this->id);

				LabReportPeer::addSelectColumns($criteria);
				if (!isset($this->lastLabReportCriteria) || !$this->lastLabReportCriteria->equals($criteria)) {
					$this->collLabReports = LabReportPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastLabReportCriteria = $criteria;
		return $this->collLabReports;
	}

	/**
	 * Returns the number of related LabReport objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related LabReport objects.
	 * @throws     PropelException
	 */
	public function countLabReports(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PatientPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collLabReports === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(LabReportPeer::PATIENT_ID, $this->id);

				$count = LabReportPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(LabReportPeer::PATIENT_ID, $this->id);

				if (!isset($this->lastLabReportCriteria) || !$this->lastLabReportCriteria->equals($criteria)) {
					$count = LabReportPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collLabReports);
				}
			} else {
				$count = count($this->collLabReports);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a LabReport object to this object
	 * through the LabReport foreign key attribute.
	 *
	 * @param      LabReport $l LabReport
	 * @return     void
	 * @throws     PropelException
	 */
	public function addLabReport(LabReport $l)
	{
		if ($this->collLabReports === null) {
			$this->initLabReports();
		}
		if (!in_array($l, $this->collLabReports, true)) { // only add it if the **same** object is not already associated
			array_push($this->collLabReports, $l);
			$l->setPatient($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Patient is new, it will return
	 * an empty collection; or if this Patient has previously
	 * been saved, it will retrieve related LabReports from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Patient.
	 */
	public function getLabReportsJoinVisit($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PatientPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collLabReports === null) {
			if ($this->isNew()) {
				$this->collLabReports = array();
			} else {

				$criteria->add(LabReportPeer::PATIENT_ID, $this->id);

				$this->collLabReports = LabReportPeer::doSelectJoinVisit($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(LabReportPeer::PATIENT_ID, $this->id);

			if (!isset($this->lastLabReportCriteria) || !$this->lastLabReportCriteria->equals($criteria)) {
				$this->collLabReports = LabReportPeer::doSelectJoinVisit($criteria, $con, $join_behavior);
			}
		}
		$this->lastLabReportCriteria = $criteria;

		return $this->collLabReports;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Patient is new, it will return
	 * an empty collection; or if this Patient has previously
	 * been saved, it will retrieve related LabReports from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Patient.
	 */
	public function getLabReportsJoinLabTest($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PatientPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collLabReports === null) {
			if ($this->isNew()) {
				$this->collLabReports = array();
			} else {

				$criteria->add(LabReportPeer::PATIENT_ID, $this->id);

				$this->collLabReports = LabReportPeer::doSelectJoinLabTest($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(LabReportPeer::PATIENT_ID, $this->id);

			if (!isset($this->lastLabReportCriteria) || !$this->lastLabReportCriteria->equals($criteria)) {
				$this->collLabReports = LabReportPeer::doSelectJoinLabTest($criteria, $con, $join_behavior);
			}
		}
		$this->lastLabReportCriteria = $criteria;

		return $this->collLabReports;
	}

	/**
	 * Clears out the collVisits collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addVisits()
	 */
	public function clearVisits()
	{
		$this->collVisits = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collVisits collection (array).
	 *
	 * By default this just sets the collVisits collection to an empty array (like clearcollVisits());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initVisits()
	{
		$this->collVisits = array();
	}

	/**
	 * Gets an array of Visit objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Patient has previously been saved, it will retrieve
	 * related Visits from storage. If this Patient is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Visit[]
	 * @throws     PropelException
	 */
	public function getVisits($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PatientPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collVisits === null) {
			if ($this->isNew()) {
			   $this->collVisits = array();
			} else {

				$criteria->add(VisitPeer::PATIENT_ID, $this->id);

				VisitPeer::addSelectColumns($criteria);
				$this->collVisits = VisitPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(VisitPeer::PATIENT_ID, $this->id);

				VisitPeer::addSelectColumns($criteria);
				if (!isset($this->lastVisitCriteria) || !$this->lastVisitCriteria->equals($criteria)) {
					$this->collVisits = VisitPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastVisitCriteria = $criteria;
		return $this->collVisits;
	}

	/**
	 * Returns the number of related Visit objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Visit objects.
	 * @throws     PropelException
	 */
	public function countVisits(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PatientPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collVisits === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(VisitPeer::PATIENT_ID, $this->id);

				$count = VisitPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(VisitPeer::PATIENT_ID, $this->id);

				if (!isset($this->lastVisitCriteria) || !$this->lastVisitCriteria->equals($criteria)) {
					$count = VisitPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collVisits);
				}
			} else {
				$count = count($this->collVisits);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Visit object to this object
	 * through the Visit foreign key attribute.
	 *
	 * @param      Visit $l Visit
	 * @return     void
	 * @throws     PropelException
	 */
	public function addVisit(Visit $l)
	{
		if ($this->collVisits === null) {
			$this->initVisits();
		}
		if (!in_array($l, $this->collVisits, true)) { // only add it if the **same** object is not already associated
			array_push($this->collVisits, $l);
			$l->setPatient($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Patient is new, it will return
	 * an empty collection; or if this Patient has previously
	 * been saved, it will retrieve related Visits from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Patient.
	 */
	public function getVisitsJoinEmployeeRelatedByDoctorId($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PatientPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collVisits === null) {
			if ($this->isNew()) {
				$this->collVisits = array();
			} else {

				$criteria->add(VisitPeer::PATIENT_ID, $this->id);

				$this->collVisits = VisitPeer::doSelectJoinEmployeeRelatedByDoctorId($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(VisitPeer::PATIENT_ID, $this->id);

			if (!isset($this->lastVisitCriteria) || !$this->lastVisitCriteria->equals($criteria)) {
				$this->collVisits = VisitPeer::doSelectJoinEmployeeRelatedByDoctorId($criteria, $con, $join_behavior);
			}
		}
		$this->lastVisitCriteria = $criteria;

		return $this->collVisits;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Patient is new, it will return
	 * an empty collection; or if this Patient has previously
	 * been saved, it will retrieve related Visits from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Patient.
	 */
	public function getVisitsJoinWardBed($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PatientPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collVisits === null) {
			if ($this->isNew()) {
				$this->collVisits = array();
			} else {

				$criteria->add(VisitPeer::PATIENT_ID, $this->id);

				$this->collVisits = VisitPeer::doSelectJoinWardBed($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(VisitPeer::PATIENT_ID, $this->id);

			if (!isset($this->lastVisitCriteria) || !$this->lastVisitCriteria->equals($criteria)) {
				$this->collVisits = VisitPeer::doSelectJoinWardBed($criteria, $con, $join_behavior);
			}
		}
		$this->lastVisitCriteria = $criteria;

		return $this->collVisits;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Patient is new, it will return
	 * an empty collection; or if this Patient has previously
	 * been saved, it will retrieve related Visits from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Patient.
	 */
	public function getVisitsJoinEmployeeRelatedByWardDocId($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PatientPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collVisits === null) {
			if ($this->isNew()) {
				$this->collVisits = array();
			} else {

				$criteria->add(VisitPeer::PATIENT_ID, $this->id);

				$this->collVisits = VisitPeer::doSelectJoinEmployeeRelatedByWardDocId($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(VisitPeer::PATIENT_ID, $this->id);

			if (!isset($this->lastVisitCriteria) || !$this->lastVisitCriteria->equals($criteria)) {
				$this->collVisits = VisitPeer::doSelectJoinEmployeeRelatedByWardDocId($criteria, $con, $join_behavior);
			}
		}
		$this->lastVisitCriteria = $criteria;

		return $this->collVisits;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collLabReports) {
				foreach ((array) $this->collLabReports as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collVisits) {
				foreach ((array) $this->collVisits as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collLabReports = null;
		$this->collVisits = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BasePatient:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BasePatient::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BasePatient
