<?php

/**
 * Base class that represents a row from the 'visit_medicine' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 06/23/11 11:44:31
 *
 * @package    lib.model.om
 */
abstract class BaseVisitMedicine extends BaseObject  implements Persistent {


  const PEER = 'VisitMedicinePeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        VisitMedicinePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the patient_id field.
	 * @var        int
	 */
	protected $patient_id;

	/**
	 * The value for the visit_id field.
	 * @var        int
	 */
	protected $visit_id;

	/**
	 * The value for the pharma_id field.
	 * @var        int
	 */
	protected $pharma_id;

	/**
	 * The value for the dosage_id field.
	 * @var        int
	 */
	protected $dosage_id;

	/**
	 * The value for the quantity field.
	 * @var        int
	 */
	protected $quantity;

	/**
	 * The value for the price field.
	 * @var        int
	 */
	protected $price;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        Patient
	 */
	protected $aPatient;

	/**
	 * @var        Visit
	 */
	protected $aVisit;

	/**
	 * @var        Pharma
	 */
	protected $aPharma;

	/**
	 * @var        Dosage
	 */
	protected $aDosage;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseVisitMedicine object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [patient_id] column value.
	 * 
	 * @return     int
	 */
	public function getPatientId()
	{
		return $this->patient_id;
	}

	/**
	 * Get the [visit_id] column value.
	 * 
	 * @return     int
	 */
	public function getVisitId()
	{
		return $this->visit_id;
	}

	/**
	 * Get the [pharma_id] column value.
	 * 
	 * @return     int
	 */
	public function getPharmaId()
	{
		return $this->pharma_id;
	}

	/**
	 * Get the [dosage_id] column value.
	 * 
	 * @return     int
	 */
	public function getDosageId()
	{
		return $this->dosage_id;
	}

	/**
	 * Get the [quantity] column value.
	 * 
	 * @return     int
	 */
	public function getQuantity()
	{
		return $this->quantity;
	}

	/**
	 * Get the [price] column value.
	 * 
	 * @return     int
	 */
	public function getPrice()
	{
		return $this->price;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     VisitMedicine The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = VisitMedicinePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [patient_id] column.
	 * 
	 * @param      int $v new value
	 * @return     VisitMedicine The current object (for fluent API support)
	 */
	public function setPatientId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->patient_id !== $v) {
			$this->patient_id = $v;
			$this->modifiedColumns[] = VisitMedicinePeer::PATIENT_ID;
		}

		if ($this->aPatient !== null && $this->aPatient->getId() !== $v) {
			$this->aPatient = null;
		}

		return $this;
	} // setPatientId()

	/**
	 * Set the value of [visit_id] column.
	 * 
	 * @param      int $v new value
	 * @return     VisitMedicine The current object (for fluent API support)
	 */
	public function setVisitId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->visit_id !== $v) {
			$this->visit_id = $v;
			$this->modifiedColumns[] = VisitMedicinePeer::VISIT_ID;
		}

		if ($this->aVisit !== null && $this->aVisit->getId() !== $v) {
			$this->aVisit = null;
		}

		return $this;
	} // setVisitId()

	/**
	 * Set the value of [pharma_id] column.
	 * 
	 * @param      int $v new value
	 * @return     VisitMedicine The current object (for fluent API support)
	 */
	public function setPharmaId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->pharma_id !== $v) {
			$this->pharma_id = $v;
			$this->modifiedColumns[] = VisitMedicinePeer::PHARMA_ID;
		}

		if ($this->aPharma !== null && $this->aPharma->getId() !== $v) {
			$this->aPharma = null;
		}

		return $this;
	} // setPharmaId()

	/**
	 * Set the value of [dosage_id] column.
	 * 
	 * @param      int $v new value
	 * @return     VisitMedicine The current object (for fluent API support)
	 */
	public function setDosageId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->dosage_id !== $v) {
			$this->dosage_id = $v;
			$this->modifiedColumns[] = VisitMedicinePeer::DOSAGE_ID;
		}

		if ($this->aDosage !== null && $this->aDosage->getId() !== $v) {
			$this->aDosage = null;
		}

		return $this;
	} // setDosageId()

	/**
	 * Set the value of [quantity] column.
	 * 
	 * @param      int $v new value
	 * @return     VisitMedicine The current object (for fluent API support)
	 */
	public function setQuantity($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->quantity !== $v) {
			$this->quantity = $v;
			$this->modifiedColumns[] = VisitMedicinePeer::QUANTITY;
		}

		return $this;
	} // setQuantity()

	/**
	 * Set the value of [price] column.
	 * 
	 * @param      int $v new value
	 * @return     VisitMedicine The current object (for fluent API support)
	 */
	public function setPrice($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->price !== $v) {
			$this->price = $v;
			$this->modifiedColumns[] = VisitMedicinePeer::PRICE;
		}

		return $this;
	} // setPrice()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     VisitMedicine The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = VisitMedicinePeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     VisitMedicine The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = VisitMedicinePeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->patient_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->visit_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->pharma_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->dosage_id = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->quantity = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->price = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->created_at = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->updated_at = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 9; // 9 = VisitMedicinePeer::NUM_COLUMNS - VisitMedicinePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating VisitMedicine object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aPatient !== null && $this->patient_id !== $this->aPatient->getId()) {
			$this->aPatient = null;
		}
		if ($this->aVisit !== null && $this->visit_id !== $this->aVisit->getId()) {
			$this->aVisit = null;
		}
		if ($this->aPharma !== null && $this->pharma_id !== $this->aPharma->getId()) {
			$this->aPharma = null;
		}
		if ($this->aDosage !== null && $this->dosage_id !== $this->aDosage->getId()) {
			$this->aDosage = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(VisitMedicinePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = VisitMedicinePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aPatient = null;
			$this->aVisit = null;
			$this->aPharma = null;
			$this->aDosage = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseVisitMedicine:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(VisitMedicinePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			VisitMedicinePeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseVisitMedicine:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseVisitMedicine:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(VisitMedicinePeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

    if ($this->isModified() && !$this->isColumnModified(VisitMedicinePeer::UPDATED_AT))
    {
      $this->setUpdatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(VisitMedicinePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseVisitMedicine:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			VisitMedicinePeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPatient !== null) {
				if ($this->aPatient->isModified() || $this->aPatient->isNew()) {
					$affectedRows += $this->aPatient->save($con);
				}
				$this->setPatient($this->aPatient);
			}

			if ($this->aVisit !== null) {
				if ($this->aVisit->isModified() || $this->aVisit->isNew()) {
					$affectedRows += $this->aVisit->save($con);
				}
				$this->setVisit($this->aVisit);
			}

			if ($this->aPharma !== null) {
				if ($this->aPharma->isModified() || $this->aPharma->isNew()) {
					$affectedRows += $this->aPharma->save($con);
				}
				$this->setPharma($this->aPharma);
			}

			if ($this->aDosage !== null) {
				if ($this->aDosage->isModified() || $this->aDosage->isNew()) {
					$affectedRows += $this->aDosage->save($con);
				}
				$this->setDosage($this->aDosage);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = VisitMedicinePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = VisitMedicinePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += VisitMedicinePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPatient !== null) {
				if (!$this->aPatient->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPatient->getValidationFailures());
				}
			}

			if ($this->aVisit !== null) {
				if (!$this->aVisit->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aVisit->getValidationFailures());
				}
			}

			if ($this->aPharma !== null) {
				if (!$this->aPharma->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPharma->getValidationFailures());
				}
			}

			if ($this->aDosage !== null) {
				if (!$this->aDosage->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aDosage->getValidationFailures());
				}
			}


			if (($retval = VisitMedicinePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = VisitMedicinePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getPatientId();
				break;
			case 2:
				return $this->getVisitId();
				break;
			case 3:
				return $this->getPharmaId();
				break;
			case 4:
				return $this->getDosageId();
				break;
			case 5:
				return $this->getQuantity();
				break;
			case 6:
				return $this->getPrice();
				break;
			case 7:
				return $this->getCreatedAt();
				break;
			case 8:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = VisitMedicinePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getPatientId(),
			$keys[2] => $this->getVisitId(),
			$keys[3] => $this->getPharmaId(),
			$keys[4] => $this->getDosageId(),
			$keys[5] => $this->getQuantity(),
			$keys[6] => $this->getPrice(),
			$keys[7] => $this->getCreatedAt(),
			$keys[8] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = VisitMedicinePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setPatientId($value);
				break;
			case 2:
				$this->setVisitId($value);
				break;
			case 3:
				$this->setPharmaId($value);
				break;
			case 4:
				$this->setDosageId($value);
				break;
			case 5:
				$this->setQuantity($value);
				break;
			case 6:
				$this->setPrice($value);
				break;
			case 7:
				$this->setCreatedAt($value);
				break;
			case 8:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = VisitMedicinePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setPatientId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setVisitId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setPharmaId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setDosageId($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setQuantity($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setPrice($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setCreatedAt($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setUpdatedAt($arr[$keys[8]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(VisitMedicinePeer::DATABASE_NAME);

		if ($this->isColumnModified(VisitMedicinePeer::ID)) $criteria->add(VisitMedicinePeer::ID, $this->id);
		if ($this->isColumnModified(VisitMedicinePeer::PATIENT_ID)) $criteria->add(VisitMedicinePeer::PATIENT_ID, $this->patient_id);
		if ($this->isColumnModified(VisitMedicinePeer::VISIT_ID)) $criteria->add(VisitMedicinePeer::VISIT_ID, $this->visit_id);
		if ($this->isColumnModified(VisitMedicinePeer::PHARMA_ID)) $criteria->add(VisitMedicinePeer::PHARMA_ID, $this->pharma_id);
		if ($this->isColumnModified(VisitMedicinePeer::DOSAGE_ID)) $criteria->add(VisitMedicinePeer::DOSAGE_ID, $this->dosage_id);
		if ($this->isColumnModified(VisitMedicinePeer::QUANTITY)) $criteria->add(VisitMedicinePeer::QUANTITY, $this->quantity);
		if ($this->isColumnModified(VisitMedicinePeer::PRICE)) $criteria->add(VisitMedicinePeer::PRICE, $this->price);
		if ($this->isColumnModified(VisitMedicinePeer::CREATED_AT)) $criteria->add(VisitMedicinePeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(VisitMedicinePeer::UPDATED_AT)) $criteria->add(VisitMedicinePeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(VisitMedicinePeer::DATABASE_NAME);

		$criteria->add(VisitMedicinePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of VisitMedicine (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setPatientId($this->patient_id);

		$copyObj->setVisitId($this->visit_id);

		$copyObj->setPharmaId($this->pharma_id);

		$copyObj->setDosageId($this->dosage_id);

		$copyObj->setQuantity($this->quantity);

		$copyObj->setPrice($this->price);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     VisitMedicine Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     VisitMedicinePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new VisitMedicinePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Patient object.
	 *
	 * @param      Patient $v
	 * @return     VisitMedicine The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPatient(Patient $v = null)
	{
		if ($v === null) {
			$this->setPatientId(NULL);
		} else {
			$this->setPatientId($v->getId());
		}

		$this->aPatient = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Patient object, it will not be re-added.
		if ($v !== null) {
			$v->addVisitMedicine($this);
		}

		return $this;
	}


	/**
	 * Get the associated Patient object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Patient The associated Patient object.
	 * @throws     PropelException
	 */
	public function getPatient(PropelPDO $con = null)
	{
		if ($this->aPatient === null && ($this->patient_id !== null)) {
			$c = new Criteria(PatientPeer::DATABASE_NAME);
			$c->add(PatientPeer::ID, $this->patient_id);
			$this->aPatient = PatientPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPatient->addVisitMedicines($this);
			 */
		}
		return $this->aPatient;
	}

	/**
	 * Declares an association between this object and a Visit object.
	 *
	 * @param      Visit $v
	 * @return     VisitMedicine The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setVisit(Visit $v = null)
	{
		if ($v === null) {
			$this->setVisitId(NULL);
		} else {
			$this->setVisitId($v->getId());
		}

		$this->aVisit = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Visit object, it will not be re-added.
		if ($v !== null) {
			$v->addVisitMedicine($this);
		}

		return $this;
	}


	/**
	 * Get the associated Visit object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Visit The associated Visit object.
	 * @throws     PropelException
	 */
	public function getVisit(PropelPDO $con = null)
	{
		if ($this->aVisit === null && ($this->visit_id !== null)) {
			$c = new Criteria(VisitPeer::DATABASE_NAME);
			$c->add(VisitPeer::ID, $this->visit_id);
			$this->aVisit = VisitPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aVisit->addVisitMedicines($this);
			 */
		}
		return $this->aVisit;
	}

	/**
	 * Declares an association between this object and a Pharma object.
	 *
	 * @param      Pharma $v
	 * @return     VisitMedicine The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPharma(Pharma $v = null)
	{
		if ($v === null) {
			$this->setPharmaId(NULL);
		} else {
			$this->setPharmaId($v->getId());
		}

		$this->aPharma = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Pharma object, it will not be re-added.
		if ($v !== null) {
			$v->addVisitMedicine($this);
		}

		return $this;
	}


	/**
	 * Get the associated Pharma object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Pharma The associated Pharma object.
	 * @throws     PropelException
	 */
	public function getPharma(PropelPDO $con = null)
	{
		if ($this->aPharma === null && ($this->pharma_id !== null)) {
			$c = new Criteria(PharmaPeer::DATABASE_NAME);
			$c->add(PharmaPeer::ID, $this->pharma_id);
			$this->aPharma = PharmaPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPharma->addVisitMedicines($this);
			 */
		}
		return $this->aPharma;
	}

	/**
	 * Declares an association between this object and a Dosage object.
	 *
	 * @param      Dosage $v
	 * @return     VisitMedicine The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setDosage(Dosage $v = null)
	{
		if ($v === null) {
			$this->setDosageId(NULL);
		} else {
			$this->setDosageId($v->getId());
		}

		$this->aDosage = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Dosage object, it will not be re-added.
		if ($v !== null) {
			$v->addVisitMedicine($this);
		}

		return $this;
	}


	/**
	 * Get the associated Dosage object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Dosage The associated Dosage object.
	 * @throws     PropelException
	 */
	public function getDosage(PropelPDO $con = null)
	{
		if ($this->aDosage === null && ($this->dosage_id !== null)) {
			$c = new Criteria(DosagePeer::DATABASE_NAME);
			$c->add(DosagePeer::ID, $this->dosage_id);
			$this->aDosage = DosagePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aDosage->addVisitMedicines($this);
			 */
		}
		return $this->aDosage;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aPatient = null;
			$this->aVisit = null;
			$this->aPharma = null;
			$this->aDosage = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseVisitMedicine:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseVisitMedicine::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseVisitMedicine
